<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GrowthDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrowthDataRepository extends EntityRepository
{

}